import type { Metadata } from "next";
import { Geist, Geist_Mono, Mali } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const mali = Mali({
  subsets: ["latin"],
  weight: ["400", "700"], // เพิ่มน้ำหนักที่ต้องการ
  variable: "--font-mali",
});

export const metadata: Metadata = {
  title: "Supakit-Profire-resume",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${mali.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
